-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."MOVIES" DROP CONSTRAINT IF EXISTS "Release Year id";

ALTER TABLE IF EXISTS public."MOVIE_ACTORS" DROP CONSTRAINT IF EXISTS "Movie key";

ALTER TABLE IF EXISTS public."MOVIE_ACTORS" DROP CONSTRAINT IF EXISTS "Actor key";

ALTER TABLE IF EXISTS public."MOVIE_DIRECTORS" DROP CONSTRAINT IF EXISTS "Movie key";

ALTER TABLE IF EXISTS public."MOVIE_DIRECTORS" DROP CONSTRAINT IF EXISTS "Director key";

ALTER TABLE IF EXISTS public."MOVIE_GENRES" DROP CONSTRAINT IF EXISTS "Movie id";

ALTER TABLE IF EXISTS public."MOVIE_GENRES" DROP CONSTRAINT IF EXISTS "Genre id";

ALTER TABLE IF EXISTS public."ADDITIONAL_MOVIE_DATA" DROP CONSTRAINT IF EXISTS "Movie id";

ALTER TABLE IF EXISTS public."FAVOURITE_MOVIES" DROP CONSTRAINT IF EXISTS "Movie Id";

ALTER TABLE IF EXISTS public."FAVOURITE_MOVIES" DROP CONSTRAINT IF EXISTS "User id";



DROP TABLE IF EXISTS public."MOVIES";

CREATE TABLE IF NOT EXISTS public."MOVIES"
(
    movie_id uuid NOT NULL,
    movie_name "char"[] NOT NULL,
    movie_rating double precision DEFAULT 0.0,
    movie_license_period daterange,
    movie_release_year_id uuid NOT NULL,
    contributors_id uuid NOT NULL,
    PRIMARY KEY (movie_id)
);

COMMENT ON TABLE public."MOVIES"
    IS 'Table of movies with their meta data and id';

DROP TABLE IF EXISTS public."DIRECTORS";

CREATE TABLE IF NOT EXISTS public."DIRECTORS"
(
    director_id uuid NOT NULL,
    first_name text NOT NULL,
    middle_name text,
    last_name text NOT NULL,
    PRIMARY KEY (director_id)
);

COMMENT ON TABLE public."DIRECTORS"
    IS 'Table consist id of each director and their name';

DROP TABLE IF EXISTS public."ACTORS";

CREATE TABLE IF NOT EXISTS public."ACTORS"
(
    actor_id uuid NOT NULL,
    first_name text NOT NULL,
    middle_name text,
    last_name text NOT NULL,
    PRIMARY KEY (actor_id)
);

COMMENT ON TABLE public."ACTORS"
    IS 'Table consist id of each actor and their name, middle name and surname';

DROP TABLE IF EXISTS public."MOVIE_ACTORS";

CREATE TABLE IF NOT EXISTS public."MOVIE_ACTORS"
(
    movie_id uuid NOT NULL,
    actor_id uuid NOT NULL
);

COMMENT ON TABLE public."MOVIE_ACTORS"
    IS 'Table that join actors and movies together. MANY-to-MANY';

DROP TABLE IF EXISTS public."MOVIE_DIRECTORS";

CREATE TABLE IF NOT EXISTS public."MOVIE_DIRECTORS"
(
    movie_id uuid NOT NULL,
    director_id uuid NOT NULL
);

COMMENT ON TABLE public."MOVIE_DIRECTORS"
    IS 'Table that join directors and movies together. MANY-to-MANY';

DROP TABLE IF EXISTS public."GENRES";

CREATE TABLE IF NOT EXISTS public."GENRES"
(
    genre_id uuid NOT NULL,
    genre_name text NOT NULL,
    genre_description text NOT NULL,
    PRIMARY KEY (genre_id)
);

COMMENT ON TABLE public."GENRES"
    IS 'Table of movie GENRES descriptions and ect....';

DROP TABLE IF EXISTS public."MOVIE_GENRES";

CREATE TABLE IF NOT EXISTS public."MOVIE_GENRES"
(
    movie_id uuid NOT NULL,
    genre_id uuid NOT NULL
);

COMMENT ON TABLE public."MOVIE_GENRES"
    IS 'Table that join movies genres and movies and are related to them in MANY-to-MANY';

DROP TABLE IF EXISTS public."RELEASE_YEARS";

CREATE TABLE IF NOT EXISTS public."RELEASE_YEARS"
(
    release_year_id uuid NOT NULL,
    movie_release_year date NOT NULL,
    PRIMARY KEY (release_year_id)
);

COMMENT ON TABLE public."RELEASE_YEARS"
    IS 'The table with all years when existing in movie table movies was released';

DROP TABLE IF EXISTS public."ADDITIONAL_MOVIE_DATA";

CREATE TABLE IF NOT EXISTS public."ADDITIONAL_MOVIE_DATA"
(
    movie_id uuid NOT NULL,
    movie_poster bytea NOT NULL,
    movie_trailer text NOT NULL
);

COMMENT ON TABLE public."ADDITIONAL_MOVIE_DATA"
    IS 'Table with trailer link and movie poster';

DROP TABLE IF EXISTS public."USERS";

CREATE TABLE IF NOT EXISTS public."USERS"
(
    user_id uuid NOT NULL,
    user_login text NOT NULL,
    user_password text NOT NULL,
    user_mail text NOT NULL,
    user_is_subscripted boolean NOT NULL,
    user_subscription_period daterange,
    user_is_admin boolean NOT NULL,
    PRIMARY KEY (user_id)
);

COMMENT ON TABLE public."USERS"
    IS 'Table which will consist users';

DROP TABLE IF EXISTS public."FAVOURITE_MOVIES";

CREATE TABLE IF NOT EXISTS public."FAVOURITE_MOVIES"
(
    user_id uuid NOT NULL,
    movie_id uuid
);

COMMENT ON TABLE public."FAVOURITE_MOVIES"
    IS 'The joint table that joins movies and users using MANY-to-MANY connection';

ALTER TABLE IF EXISTS public."MOVIES"
    ADD CONSTRAINT "Release Year id" FOREIGN KEY (movie_release_year_id)
    REFERENCES public."RELEASE_YEARS" (release_year_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Release Year id" ON public."MOVIES"
    IS 'FK or year when movie was released';



ALTER TABLE IF EXISTS public."MOVIE_ACTORS"
    ADD CONSTRAINT "Movie key" FOREIGN KEY (movie_id)
    REFERENCES public."MOVIES" (movie_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Movie key" ON public."MOVIE_ACTORS"
    IS 'FK for movies table';



ALTER TABLE IF EXISTS public."MOVIE_ACTORS"
    ADD CONSTRAINT "Actor key" FOREIGN KEY (actor_id)
    REFERENCES public."ACTORS" (actor_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Actor key" ON public."MOVIE_ACTORS"
    IS 'FK for actors table ids. MANY-to_MANY';



ALTER TABLE IF EXISTS public."MOVIE_DIRECTORS"
    ADD CONSTRAINT "Movie key" FOREIGN KEY (movie_id)
    REFERENCES public."MOVIES" (movie_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT "Movie key" ON public."MOVIE_DIRECTORS"
    IS 'KF for movies table and its id. MANY-to-MANY';



ALTER TABLE IF EXISTS public."MOVIE_DIRECTORS"
    ADD CONSTRAINT "Director key" FOREIGN KEY (director_id)
    REFERENCES public."DIRECTORS" (director_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Director key" ON public."MOVIE_DIRECTORS"
    IS 'FK for directors table and their ids, MANY-to-MANY';



ALTER TABLE IF EXISTS public."MOVIE_GENRES"
    ADD CONSTRAINT "Movie id" FOREIGN KEY (movie_id)
    REFERENCES public."MOVIES" (movie_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Movie id" ON public."MOVIE_GENRES"
    IS 'FK for movie table';



ALTER TABLE IF EXISTS public."MOVIE_GENRES"
    ADD CONSTRAINT "Genre id" FOREIGN KEY (genre_id)
    REFERENCES public."GENRES" (genre_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Genre id" ON public."MOVIE_GENRES"
    IS 'FK for genres table';



ALTER TABLE IF EXISTS public."ADDITIONAL_MOVIE_DATA"
    ADD CONSTRAINT "Movie id" FOREIGN KEY (movie_id)
    REFERENCES public."MOVIES" (movie_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

COMMENT ON CONSTRAINT "Movie id" ON public."ADDITIONAL_MOVIE_DATA"
    IS 'FK to PK of movies table';



ALTER TABLE IF EXISTS public."FAVOURITE_MOVIES"
    ADD CONSTRAINT "Movie Id" FOREIGN KEY (movie_id)
    REFERENCES public."MOVIES" (movie_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT "Movie Id" ON public."FAVOURITE_MOVIES"
    IS 'FK to movies table';



ALTER TABLE IF EXISTS public."FAVOURITE_MOVIES"
    ADD CONSTRAINT "User id" FOREIGN KEY (user_id)
    REFERENCES public."USERS" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT "User id" ON public."FAVOURITE_MOVIES"
    IS 'FK for user in users table ';


END;