from dumb_data_generation.actors_dumb_data_generation import insert_dumb_data_actors
from dumb_data_generation.additional_movie_data_generation import insert_dumb_data_additional_movie_data
from dumb_data_generation.directors_dumb_data_generation import insert_dumb_data_directors
from dumb_data_generation.genres_dumb_data_generation import insert_dumb_data_genres
from dumb_data_generation.licenses_dumb_data_generation import insert_dumb_data_licenses
from dumb_data_generation.movie_localization_dumb_data_generation import insert_dumb_data_movie_localizations
from dumb_data_generation.movies_dumb_data_generation import insert_dumb_data_movies
from dumb_data_generation.subscriptions_plans_dumb_data_generation import insert_dumb_data_subscriptions_plans
from dumb_data_generation.users_dumb_data_generation import insert_dumb_data_users_table
from dumb_data_generation.join_tables_dumb_data_generation import insert_dumb_data_fav_movies_join_tables
from dumb_data_generation.join_tables_dumb_data_generation import  insert_dumb_data_directors_join_tables
from dumb_data_generation.join_tables_dumb_data_generation import  insert_dumb_data_actors_join_tables
from dumb_data_generation.join_tables_dumb_data_generation import  insert_dumb_data_genres_join_tables
from dumb_data_generation.join_tables_dumb_data_generation import insert_dumb_data_licenses_join_tables

# insert_dumb_data_subscriptions_plans()
# insert_dumb_data_users_table()
# insert_dumb_data_movie_localizations()
# insert_dumb_data_licenses()
# insert_dumb_data_additional_movie_data()
# insert_dumb_data_directors()
# insert_dumb_data_actors()
# insert_dumb_data_genres()
# insert_dumb_data_movies()

#insert_dumb_data_fav_movies_join_tables()
#insert_dumb_data_directors_join_tables()
#insert_dumb_data_actors_join_tables()
#insert_dumb_data_genres_join_tables()
#insert_dumb_data_licenses_join_tables()
